### PR TITLE
updated intl constraints to 18.0.0

### PR DESCRIPTION
**Pull request by erickgon92**
updated libraries intl 18.0.0

### CODE REVIEW

**Comment by anilaydinn** [comment]
we are waiting this one

**Comment by EBBozkurt** [comment]
This pull request is important, we are waiting too.

**Comment by MasIzzudin** [comment]
still waiting

**Comment by SavageryCode** [comment]
Can we please get this pull done need it urgently

**Comment by koai-dev** [comment]
> date_time_picker:
    git:
      url: https://github.com/koai-dev/date_time_picker.git

**Comment by VasilisPH** [comment]
> > date_time_picker:
> > git:
> > url: https://github.com/koai-dev/date_time_picker.git

Hey ! Thanks for it.

**Review by mzdm — APPROVED** [review]

**Pull request closed without merging**
